import { test, expect } from '@playwright/test';
import path from 'node:path';

test('wipe handle drags and responds to keys without navigating photos, including after zoom', async ({page}) => {
  await page.request.post('/api/reset');
  await page.goto('/');
  await page.locator('input[type=file]').setInputFiles([1,2,3].map(i => path.resolve('e2e/fixtures', `photo-${i}.png`)));
  await expect(page.locator('.photo-card')).toHaveCount(3);
  await expect(page.getByRole('button',{name:'100%',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'현재 정합',exact:true}).click();
  await expect(page.getByRole('button',{name:'현재 정합',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'와이프',exact:true}).click();
  const handle = page.getByRole('slider',{name:'와이프 경계 이동',exact:true});
  await expect(handle).toBeVisible();
  const pane = page.locator('.photo-viewport');
  const box = (await pane.boundingBox())!;
  const knob = (await handle.boundingBox())!;
  await page.mouse.move(knob.x + knob.width/2, knob.y + knob.height/2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width*.75, knob.y + knob.height/2, {steps:5});
  await page.mouse.up();
  await expect(handle).toHaveAttribute('aria-valuenow','75');
  await expect(handle).toBeFocused();
  await expect(page.getByRole('slider',{name:'와이프 경계',exact:true})).toHaveValue(/7[45]/);
  const name = await page.getByTestId('active-name').textContent();
  await handle.press('ArrowRight');
  await expect(handle).toHaveAttribute('aria-valuenow','76');
  await expect(page.getByTestId('active-name')).toHaveText(name!);
  await handle.press('Home');
  await expect(handle).toHaveAttribute('aria-valuenow','0');
  const edge = (await handle.boundingBox())!;
  expect(edge.x).toBeGreaterThanOrEqual(box.x);
  await handle.press('End');
  await expect(handle).toHaveAttribute('aria-valuenow','100');
  await pane.hover();
  await page.mouse.wheel(0,-1100);
  await handle.press('Home');
  for (let i=0;i<5;i++) await handle.press('Shift+ArrowRight');
  await expect(handle).toHaveAttribute('aria-valuenow','50');
  const middle = (await handle.boundingBox())!;
  expect(Math.abs(middle.x + middle.width/2 - (box.x + box.width/2))).toBeLessThan(3);
  await page.getByRole('button',{name:'화면 맞춤 0',exact:true}).click();
  await page.screenshot({path:'test-results/wipe-handle.png'});
});
